// Sample data for creator preview mode
export const SAMPLE_LEADS = [
  {
    id: 'sample-1',
    referral_partner_id: 'preview-user-id',
    first_name: 'James',
    last_name: 'Wilson',
    email: 'james.wilson@email.com',
    phone: '0412 345 678',
    loan_amount: 650000,
    loan_purpose: 'Home Purchase',
    status: 'new',
    custom_fields: {},
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sample-2',
    referral_partner_id: 'preview-user-id',
    first_name: 'Sarah',
    last_name: 'Chen',
    email: 'sarah.chen@email.com',
    phone: '0423 456 789',
    loan_amount: 1200000,
    loan_purpose: 'Investment Property',
    status: 'contacted',
    custom_fields: {},
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sample-3',
    referral_partner_id: 'preview-user-id',
    first_name: 'Michael',
    last_name: 'Thompson',
    email: 'michael.t@email.com',
    phone: '0434 567 890',
    loan_amount: 450000,
    loan_purpose: 'Refinance',
    status: 'in_progress',
    custom_fields: {},
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sample-4',
    referral_partner_id: 'preview-user-id',
    first_name: 'Emily',
    last_name: 'Rodriguez',
    email: 'emily.r@email.com',
    phone: '0445 678 901',
    loan_amount: 800000,
    loan_purpose: 'Home Purchase',
    status: 'approved',
    custom_fields: {},
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'sample-5',
    referral_partner_id: 'preview-user-id',
    first_name: 'David',
    last_name: 'Patel',
    email: 'david.patel@email.com',
    phone: '0456 789 012',
    loan_amount: 320000,
    loan_purpose: 'Personal',
    status: 'settled',
    custom_fields: {},
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_NOTES: Record<string, Array<{ id: string; content: string; notify_partner: boolean; created_at: string; author_id: string | null }>> = {
  'sample-1': [],
  'sample-2': [
    {
      id: 'note-1',
      content: 'Called the client and she is going to call me back after 5pm today.',
      notify_partner: true,
      created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      author_id: 'broker-1',
    },
  ],
  'sample-3': [
    {
      id: 'note-2',
      content: 'Initial consultation completed. Client is looking to refinance existing home loan. Currently with ANZ at 6.2%. We can offer 5.89%.',
      notify_partner: true,
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      author_id: 'broker-1',
    },
    {
      id: 'note-3',
      content: 'Documents requested: payslips, bank statements, current loan statement.',
      notify_partner: false,
      created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      author_id: 'broker-1',
    },
  ],
  'sample-4': [
    {
      id: 'note-4',
      content: 'Application submitted to lender. Pre-approval received within 24hrs.',
      notify_partner: true,
      created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      author_id: 'broker-1',
    },
    {
      id: 'note-5',
      content: 'Formal approval received! Settlement date set for 15th March.',
      notify_partner: true,
      created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      author_id: 'broker-1',
    },
  ],
  'sample-5': [
    {
      id: 'note-6',
      content: 'Loan settled successfully. Commission paid.',
      notify_partner: true,
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      author_id: 'broker-1',
    },
  ],
};

export const SAMPLE_COMPANIES = [
  { id: 'company-1', name: 'Ray White Glenroy', address: '45 Wheatsheaf Rd, Glenroy VIC 3046', phone: '03 9306 1234', email: 'glenroy@raywhite.com', website: 'https://raywhite.com/glenroy', notes: 'Key partner since 2023', created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'company-2', name: 'LJ Hooker Essendon', address: '123 Mt Alexander Rd, Essendon VIC 3040', phone: '03 9379 5678', email: 'essendon@ljhooker.com', website: 'https://ljhooker.com.au', notes: null, created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString() },
];

export const SAMPLE_REFERRERS = [
  { id: 'ref-1', user_id: 'partner-1', full_name: 'Tom Nguyen', email: 'tom@raywhite.com', phone: '0412 111 222', company_name: 'Ray White Glenroy', company_id: 'company-1', date_of_birth: '1988-03-15', spouse_name: 'Lisa', interests: 'Golf, AFL', address: '12 Smith St, Glenroy VIC', license_number: null, custom_fields: { 'Preferred Contact': 'Text message' }, broker_notes: 'Great relationship, always follows up quickly.', created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ref-2', user_id: 'partner-2', full_name: 'Amy Tran', email: 'amy@ljhooker.com', phone: '0423 333 444', company_name: 'LJ Hooker Essendon', company_id: 'company-2', date_of_birth: '1992-07-22', spouse_name: null, interests: 'Running, Travel', address: null, license_number: 'RE-44521', custom_fields: {}, broker_notes: null, created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ref-3', user_id: 'preview-user-id', full_name: 'Creator Preview', email: 'creator@marginfinance.com', phone: '0400 000 000', company_name: null, company_id: null, date_of_birth: null, spouse_name: null, interests: null, address: null, license_number: null, custom_fields: {}, broker_notes: null, created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
];

// Update sample leads with different referral partners
export const SAMPLE_LEADS_WITH_REFERRERS = SAMPLE_LEADS.map((l, i) => ({
  ...l,
  referral_partner_id: i < 2 ? 'partner-1' : i < 4 ? 'partner-2' : 'preview-user-id',
  referrer_commission: i === 4 ? 500 : null,
  referrer_commission_type: 'on_settlement',
  referrer_commission_paid: i === 4,
  company_commission: i === 4 ? 2000 : i === 3 ? 1500 : null,
  company_commission_type: 'on_settlement',
  company_commission_paid: i === 4,
}));

export const SAMPLE_TASKS = [
  {
    id: 'task-1',
    lead_id: 'sample-1',
    title: 'Call James Wilson back',
    description: 'Follow up on home purchase enquiry',
    due_date: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    completed: false,
    completed_at: null,
    created_by: 'broker-1',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    lead_name: 'James Wilson',
  },
  {
    id: 'task-2',
    lead_id: 'sample-3',
    title: 'Collect documents from Michael',
    description: 'Payslips, bank statements, current loan statement',
    due_date: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    completed_at: null,
    created_by: 'broker-1',
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    lead_name: 'Michael Thompson',
  },
  {
    id: 'task-3',
    lead_id: 'sample-2',
    title: 'Send rate comparison to Sarah',
    description: 'Compare investment property rates across 3 lenders',
    due_date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completed: false,
    completed_at: null,
    created_by: 'broker-1',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    lead_name: 'Sarah Chen',
  },
  {
    id: 'task-4',
    lead_id: 'sample-4',
    title: 'Confirm settlement date with Emily',
    description: null,
    due_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed: true,
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'broker-1',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    lead_name: 'Emily Rodriguez',
  },
];
