import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ScenarioInputs, ScenarioOutputs } from "@/lib/feasibility/types";
import { PDF_COLORS, safeFormatCurrency, drawCard, drawSectionTitle, drawLabel, drawValue, drawDivider, loadImageAsBase64 } from "./pdfPrimitives";
import logoSrc from "@/assets/logo-icon.png";

const fmt = (v: number) => safeFormatCurrency(v);
const pct = (v: number) => (v * 100).toFixed(1) + "%";

export async function generateFeasibilityPdf(inputs: ScenarioInputs, outputs: ScenarioOutputs) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const mx = 14;
  const cw = pw - mx * 2;
  let y = 14;

  // Load logo
  let logoData: { base64: string; width: number; height: number } | null = null;
  try { logoData = await loadImageAsBase64(logoSrc); } catch {}

  const addHeader = () => {
    doc.setFillColor(...PDF_COLORS.dark);
    doc.rect(0, 0, pw, 28, "F");
    if (logoData) doc.addImage(logoData.base64, "PNG", mx, 5, 18, 18);
    doc.setFont("helvetica", "bold"); doc.setFontSize(16); doc.setTextColor(255, 255, 255);
    doc.text("Development Feasibility Report", mx + 22, 14);
    doc.setFontSize(9); doc.setFont("helvetica", "normal");
    doc.text(`${inputs.project_name || "Untitled"} — ${inputs.location || ""}`, mx + 22, 21);
    doc.text(inputs.name, pw - mx, 14, { align: "right" });
    doc.text(new Date().toLocaleDateString("en-AU"), pw - mx, 21, { align: "right" });
  };

  const addFooter = (pageNum: number) => {
    doc.setFontSize(7); doc.setTextColor(...PDF_COLORS.lightMuted);
    doc.text(`Page ${pageNum}`, pw - mx, ph - 6, { align: "right" });
    doc.text("Generated by Margin Mate", mx, ph - 6);
  };

  const checkPage = (need: number, pageRef: { num: number }) => {
    if (y + need > ph - 16) {
      addFooter(pageRef.num);
      doc.addPage();
      pageRef.num++;
      y = 14;
    }
  };

  const pageRef = { num: 1 };

  // ── Page 1: Header + Key Outputs ──
  addHeader();
  y = 36;

  // Key Outputs grid
  y = drawSectionTitle(doc, mx, y, "Key Outputs", 13);
  const kpiData: [string, string][] = [
    ["Total Revenue", fmt(outputs.gross_revenue)],
    ["Dev Cost (ex Interest)", fmt(outputs.total_dev_cost_ex_interest)],
    ["Total Interest", fmt(outputs.total_interest)],
    ["Dev Cost (inc Interest)", fmt(outputs.total_dev_cost_inc_interest)],
    ["Gross Profit", fmt(outputs.gross_profit)],
    ["Tax", fmt(outputs.tax)],
    ["Net Profit", fmt(outputs.net_profit_after_tax)],
    ["Total Equity Required", fmt(outputs.total_equity_required)],
    ["Peak Debt", fmt(outputs.peak_debt)],
    ["Peak Monthly CF", fmt(outputs.peak_monthly_cashflow)],
    ["Equity Multiple", outputs.equity_multiple.toFixed(2) + "x"],
    ["Cost / Unit", fmt(outputs.cost_per_unit)],
    ["Revenue / Unit", fmt(outputs.revenue_per_unit)],
    ["Profit / Unit", fmt(outputs.profit_per_unit)],
  ];

  const cols = 3;
  const cardW = (cw - (cols - 1) * 4) / cols;
  const cardH = 18;
  kpiData.forEach(([label, value], i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    if (col === 0 && row > 0) checkPage(cardH + 4, pageRef);
    const cx = mx + col * (cardW + 4);
    const cy = y + row * (cardH + 3);
    drawCard(doc, cx, cy, cardW, cardH);
    drawLabel(doc, cx + 4, cy + 7, label, 7);
    drawValue(doc, cx + 4, cy + 14, value, 11);
  });
  y += Math.ceil(kpiData.length / cols) * (cardH + 3) + 6;

  // Optional costs
  const optCosts = [
    outputs.council_contributions > 0 && ["Council/Headworks", fmt(outputs.council_contributions)],
    outputs.arch_eng_fees > 0 && ["Arch/Eng Fees", fmt(outputs.arch_eng_fees)],
    outputs.qs_pm_fees > 0 && ["QS/PM Fees", fmt(outputs.qs_pm_fees)],
    outputs.marketing_staging > 0 && ["Marketing/Staging", fmt(outputs.marketing_staging)],
    outputs.debt_establishment_fees > 0 && ["Debt Estab. Fees", fmt(outputs.debt_establishment_fees)],
  ].filter(Boolean) as [string, string][];

  if (optCosts.length > 0) {
    checkPage(30, pageRef);
    y = drawSectionTitle(doc, mx, y, "Optional Costs Breakdown", 11);
    optCosts.forEach(([label, value], i) => {
      const cx = mx + (i % cols) * (cardW + 4);
      const cy = y + Math.floor(i / cols) * (cardH + 3);
      drawCard(doc, cx, cy, cardW, cardH);
      drawLabel(doc, cx + 4, cy + 7, label, 7);
      drawValue(doc, cx + 4, cy + 14, value, 10);
    });
    y += Math.ceil(optCosts.length / cols) * (cardH + 3) + 6;
  }

  // ── Inputs Snapshot ──
  checkPage(50, pageRef);
  y = drawSectionTitle(doc, mx, y, "Inputs Snapshot", 13);

  const inputRows = [
    ["Purchase Price", fmt(inputs.purchase_price)],
    ["Stamp Duty", fmt(outputs.stamp_duty)],
    ["Demolition", fmt(inputs.demolition_cost)],
    ["Site Total", fmt(outputs.site_total)],
    ["Soft Costs", fmt(outputs.soft_costs_total)],
    ["Build Rate/sqm", fmt(inputs.build_rate_per_sqm)],
    ["Total SQM", outputs.total_sqm.toLocaleString()],
    ["Gross Build Cost", fmt(outputs.gross_build_cost)],
    ["Build Contingency", pct(inputs.build_contingency_rate)],
    ["Total Units", String(outputs.total_units)],
    ["Pre-build Months", String(inputs.pre_build_months)],
    ["Build Duration", String(inputs.build_duration_months) + " months"],
    ["Settlement Month", String(inputs.sales_settlement_month)],
    ["Land LVR", pct(inputs.land_lvr)],
    ["Land Rate", pct(inputs.land_interest_rate_annual)],
    ["Construction LVR", pct(inputs.construction_lvr)],
    ["Construction Rate", pct(inputs.construction_interest_rate_annual)],
    ["Interest Funded", inputs.interest_funded ? "Yes" : "No"],
    ["Avg Sale Price", fmt(inputs.avg_sale_price)],
    ["Tax Rate", pct(inputs.company_tax_rate)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Input", "Value"]],
    body: inputRows,
    margin: { left: mx, right: mx },
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: PDF_COLORS.dark, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    theme: "grid",
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Partners ──
  if (outputs.partner_results.length > 0) {
    checkPage(40, pageRef);
    y = drawSectionTitle(doc, mx, y, "Partner Summary", 13);
    autoTable(doc, {
      startY: y,
      head: [["Partner", "Ownership", "Equity", "Profit", "ROE"]],
      body: outputs.partner_results.map(p => [
        p.name,
        p.ownership_percent + "%",
        fmt(p.equity_contribution),
        fmt(p.profit_distribution),
        (p.return_on_equity * 100).toFixed(1) + "%",
      ]),
      margin: { left: mx, right: mx },
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: PDF_COLORS.dark, textColor: [255, 255, 255] },
      theme: "grid",
    });
    y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Month-by-Month ──
  addFooter(pageRef.num);
  doc.addPage();
  pageRef.num++;
  y = 14;
  y = drawSectionTitle(doc, mx, y, "Month-by-Month Summary", 13);

  const monthlyHead = ["Mth", "Phase", "Site", "Soft", "Build", "Opt.", "Interest", "Revenue", "Debt", "Equity", "Net CF"];
  const monthlyBody = outputs.monthly.map(m => [
    String(m.month),
    m.phase.replace("_", " "),
    m.site_costs > 0 ? fmt(m.site_costs) : "-",
    m.soft_costs > 0 ? fmt(m.soft_costs) : "-",
    m.build_costs > 0 ? fmt(m.build_costs) : "-",
    m.optional_costs > 0 ? fmt(m.optional_costs) : "-",
    m.total_interest > 0 ? fmt(m.total_interest) : "-",
    m.revenue > 0 ? fmt(m.revenue) : "-",
    fmt(m.total_debt),
    m.equity_injection > 0 ? fmt(m.equity_injection) : "-",
    fmt(m.net_cashflow),
  ]);

  autoTable(doc, {
    startY: y,
    head: [monthlyHead],
    body: monthlyBody,
    margin: { left: mx, right: mx },
    styles: { fontSize: 6, cellPadding: 1.5 },
    headStyles: { fillColor: PDF_COLORS.dark, textColor: [255, 255, 255], fontSize: 6 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    theme: "grid",
    didDrawPage: (data) => {
      addFooter(pageRef.num);
    },
  });

  addFooter(pageRef.num);

  const filename = `${inputs.project_name || "Feasibility"}_${inputs.name}.pdf`;
  doc.save(filename.replace(/\s+/g, "_"));
}
