import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { RetirementInputs, RetirementResults, formatCurrency, formatPercent } from "@/lib/retirement/calculations";
import { PDF_COLORS, drawCard, drawSectionTitle, drawLabel, drawValue, drawDivider, loadImageAsBase64 } from "./pdfPrimitives";
import logoSrc from "@/assets/logo-icon.png";

export async function generateRetirementPdf(inputs: RetirementInputs, results: RetirementResults) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const mx = 14;
  const cw = pw - mx * 2;
  let y = 14;

  let logoData: { base64: string; width: number; height: number } | null = null;
  try { logoData = await loadImageAsBase64(logoSrc); } catch {}

  const pageRef = { num: 1 };

  const addHeader = () => {
    doc.setFillColor(...PDF_COLORS.dark);
    doc.rect(0, 0, pw, 28, "F");
    if (logoData) doc.addImage(logoData.base64, "PNG", mx, 5, 18, 18);
    doc.setFont("helvetica", "bold"); doc.setFontSize(16); doc.setTextColor(255, 255, 255);
    doc.text("Passive Income Planner", mx + 22, 14);
    doc.setFontSize(9); doc.setFont("helvetica", "normal");
    doc.text("Retirement Reverse Engineer Report", mx + 22, 21);
    doc.text(new Date().toLocaleDateString("en-AU"), pw - mx, 14, { align: "right" });
  };

  const addFooter = (pageNum: number) => {
    doc.setFontSize(7); doc.setTextColor(...PDF_COLORS.lightMuted);
    doc.text(`Page ${pageNum}`, pw - mx, ph - 6, { align: "right" });
    doc.text("Generated by Margin Mate", mx, ph - 6);
  };

  const checkPage = (need: number) => {
    if (y + need > ph - 16) {
      addFooter(pageRef.num);
      doc.addPage();
      pageRef.num++;
      y = 14;
    }
  };

  // ── Page 1 ──
  addHeader();
  y = 36;

  // Headline KPIs
  const kpis = [
    { label: "Income at Retirement", value: formatCurrency(results.incomeAtRetirement) },
    { label: "Asset Base Required", value: formatCurrency(results.assetBaseRequired) },
    { label: "Equivalent Today", value: formatCurrency(results.assetBaseToday) },
    { label: "Properties Needed", value: `${results.propertiesNeeded}` },
  ];
  const kpiW = (cw - 6) / 4;
  kpis.forEach((k, i) => {
    const kx = mx + i * (kpiW + 2);
    drawCard(doc, kx, y, kpiW, 22);
    drawLabel(doc, kx + 3, y + 7, k.label, 7);
    drawValue(doc, kx + 3, y + 16, k.value, 12, PDF_COLORS.primary);
  });
  y += 28;

  // Personal Summary
  y = drawSectionTitle(doc, mx, y, "Personal Details");
  const personalRows = [
    ["Current Age", `${inputs.currentAge}`],
    ["Retirement Age", `${inputs.retirementAge}`],
    ["Years to Retirement", `${results.yearsToRetirement}`],
    ["Desired Income (Today's $)", formatCurrency(inputs.desiredIncome) + "/yr"],
    ["Inflation Rate", formatPercent(inputs.inflationRate)],
    ["Asset Growth Rate", formatPercent(inputs.assetGrowthRate)],
    ["Withdrawal Rate", formatPercent(inputs.withdrawalRate)],
    ["CGT Rate (on 50% gain)", formatPercent(inputs.cgtRate)],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: mx, right: mx },
    head: [["Assumption", "Value"]],
    body: personalRows,
    theme: "grid",
    headStyles: { fillColor: PDF_COLORS.dark, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 80 } },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Property Plan
  checkPage(60);
  y = drawSectionTitle(doc, mx, y, "Property Plan");
  const propRows = [
    ["Property Price", formatCurrency(inputs.propertyPrice)],
    ["Deposit", `${inputs.depositPct}% (${formatCurrency(inputs.propertyPrice * inputs.depositPct / 100)})`],
    ["Purchase Costs", `${inputs.purchaseCostsPct}%`],
    ["Loan Amount", formatCurrency(results.loanPerProperty)],
    ["Loan Type", inputs.loanType === "io" ? "Interest Only" : "P&I"],
    ["Interest Rate", formatPercent(inputs.interestRate)],
    ["Loan Term", `${inputs.loanTermYears} years`],
    ["Rental Yield (gross)", formatPercent(inputs.rentalYield)],
    ["Vacancy", formatPercent(inputs.vacancyPct)],
    ["Expense Allowance", formatPercent(inputs.expenseAllowancePct)],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: mx, right: mx },
    head: [["Property Detail", "Value"]],
    body: propRows,
    theme: "grid",
    headStyles: { fillColor: PDF_COLORS.dark, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 80 } },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Purchase & Funding Breakdown
  checkPage(60);
  y = drawSectionTitle(doc, mx, y, "Purchase & Funding Breakdown");
  const fundingRows = [
    ["Property Price", formatCurrency(inputs.propertyPrice), formatCurrency(inputs.propertyPrice * results.propertiesNeeded)],
    [`Deposit (${inputs.depositPct}%)`, formatCurrency(inputs.propertyPrice * inputs.depositPct / 100), formatCurrency(inputs.propertyPrice * inputs.depositPct / 100 * results.propertiesNeeded)],
    [`Purchase Costs (${inputs.purchaseCostsPct}%)`, formatCurrency(inputs.propertyPrice * inputs.purchaseCostsPct / 100), formatCurrency(inputs.propertyPrice * inputs.purchaseCostsPct / 100 * results.propertiesNeeded)],
    ["Cash Required", formatCurrency(results.cashPerProperty), formatCurrency(results.totalCashNeeded)],
    ["Loan Amount", formatCurrency(results.loanPerProperty), formatCurrency(results.loanPerProperty * results.propertiesNeeded)],
    ["Monthly Repayment", formatCurrency(results.monthlyRepayment), formatCurrency(results.monthlyRepayment * results.propertiesNeeded)],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: mx, right: mx },
    head: [["Item", "Per Property", `Total (${results.propertiesNeeded} properties)`]],
    body: fundingRows,
    theme: "grid",
    headStyles: { fillColor: PDF_COLORS.dark, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // End Position
  checkPage(60);
  y = drawSectionTitle(doc, mx, y, "End Position at Retirement");
  const endRows = [
    ["Total Gross Value", formatCurrency(results.totalGrossValue)],
    ["Outstanding Loans", formatCurrency(-results.totalLoanBalance)],
    ["Total Capital Gain", formatCurrency(results.totalCapitalGain)],
    [`CGT Payable (${inputs.cgtRate}% on 50% gain)`, formatCurrency(-results.totalCgtPayable)],
    ["Net Investable Proceeds", formatCurrency(results.totalNetInvestable)],
    [`Passive Income (at ${formatPercent(inputs.withdrawalRate)})`, formatCurrency(results.totalNetInvestable * inputs.withdrawalRate / 100) + "/yr"],
    ["Target Income at Retirement", formatCurrency(results.incomeAtRetirement) + "/yr"],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: mx, right: mx },
    head: [["Metric", "Value"]],
    body: endRows,
    theme: "grid",
    headStyles: { fillColor: PDF_COLORS.dark, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 90 } },
    didParseCell: (data) => {
      // Highlight the net proceeds row
      if (data.row.index === 4 && data.section === "body") {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.textColor = PDF_COLORS.success;
      }
    },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Sensitivity Analysis
  checkPage(50);
  y = drawSectionTitle(doc, mx, y, "Sensitivity Analysis");
  const sensBody = results.sensitivity.map(s => [
    s.label,
    formatCurrency(s.incomeAtRetirement),
    formatCurrency(s.assetBaseRequired),
    `${s.propertiesNeeded}`,
  ]);
  autoTable(doc, {
    startY: y,
    margin: { left: mx, right: mx },
    head: [["Scenario", "Income Needed", "Assets Required", "Properties"]],
    body: sensBody,
    theme: "grid",
    headStyles: { fillColor: PDF_COLORS.dark, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    didParseCell: (data) => {
      if (data.row.index === 1 && data.section === "body") {
        data.cell.styles.fontStyle = "bold";
      }
    },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  // Disclaimer
  checkPage(20);
  drawDivider(doc, mx, y, cw);
  y += 5;
  doc.setFontSize(7); doc.setTextColor(...PDF_COLORS.lightMuted);
  const disclaimer = "This report is for illustrative purposes only. It does not constitute financial advice. Projections are based on assumptions that may not reflect actual market conditions. Seek independent financial advice before making investment decisions.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, cw);
  doc.text(disclaimerLines, mx, y);

  addFooter(pageRef.num);
  doc.save("passive-income-planner.pdf");
}
