// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List leads visible to the signed-in user, most recent first. Optionally filter by status.",
  inputSchema: {
    status: z.string().optional().describe("Filter by lead status (e.g. 'new', 'qualified', 'settled')."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("leads").select("id, first_name, last_name, email, phone, status, loan_amount, loan_purpose, created_at, settled_date, referral_partner_id").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} leads.` }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead",
  description: "Fetch full details for a single lead by id.",
  inputSchema: {
    id: z2.string().uuid().describe("Lead id (uuid).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("leads").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lead not found" }], isError: true };
    return {
      content: [{ type: "text", text: `Lead ${data.first_name ?? ""} ${data.last_name ?? ""}`.trim() }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool3({
  name: "list_tasks",
  title: "List tasks",
  description: "List tasks visible to the signed-in user. Optionally filter by completion or due window.",
  inputSchema: {
    include_completed: z3.boolean().optional().describe("Include completed tasks (default false)."),
    due_before: z3.string().optional().describe("ISO date. Only return tasks due on or before this date."),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ include_completed, due_before, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("tasks").select("id, title, description, due_date, completed, priority, lead_id, assigned_to, created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 50);
    if (!include_completed) q = q.eq("completed", false);
    if (due_before) q = q.lte("due_date", due_before);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} tasks.` }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_task_default = defineTool4({
  name: "create_task",
  title: "Create task",
  description: "Create a new task for the signed-in user. lead_id is optional for standalone tasks.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Task title."),
    description: z4.string().optional(),
    due_date: z4.string().optional().describe("ISO date (YYYY-MM-DD)."),
    priority: z4.number().int().min(1).max(3).optional().describe("1 = high, 2 = medium, 3 = low."),
    lead_id: z4.string().uuid().optional().describe("Optional lead to link.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("tasks").insert({
      title: input.title,
      description: input.description ?? null,
      due_date: input.due_date ?? null,
      priority: input.priority ?? 2,
      completed: false,
      lead_id: input.lead_id ?? null,
      created_by: ctx.getUserId(),
      assigned_to: ctx.getUserId()
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Task created: ${data?.title}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_contacts_default = defineTool5({
  name: "list_contacts",
  title: "List contacts",
  description: "List contacts (clients and referrers) visible to the signed-in user. Optional name/email search.",
  inputSchema: {
    search: z5.string().optional().describe("Case-insensitive match on name or email."),
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("contacts").select("id, first_name, last_name, email, phone, type, company, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search) {
      const s = `%${search}%`;
      q = q.or(`first_name.ilike.${s},last_name.ilike.${s},email.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} contacts.` }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-settlements.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_settlements_default = defineTool6({
  name: "list_settlements",
  title: "List settlements",
  description: "List settlements visible to the signed-in user. Optionally filter by date window.",
  inputSchema: {
    from: z6.string().optional().describe("ISO date. Only settlements on or after this settlement date."),
    to: z6.string().optional().describe("ISO date. Only settlements on or before this settlement date."),
    limit: z6.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    const gate = requireAuth(ctx);
    if (gate) return gate;
    const sb = supabaseForUser(ctx);
    let q = sb.from("settlements").select("id, client_name, loan_amount, lender, settlement_date, status, lead_source, security_address, lead_id").order("settlement_date", { ascending: false }).limit(limit ?? 50);
    if (from) q = q.gte("settlement_date", from);
    if (to) q = q.lte("settlement_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((s, r) => s + (r.loan_amount || 0), 0);
    return {
      content: [{ type: "text", text: `Found ${data?.length ?? 0} settlements totalling $${total.toLocaleString()}.` }],
      structuredContent: { settlements: data ?? [], total_loan_amount: total }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "capydxuqpclcwadhwgvz";
var mcp_default = defineMcp({
  name: "margin-connect-mcp",
  title: "Margin Connect",
  version: "0.1.0",
  instructions: "Tools for the Margin Finance Connect CRM. Read and manage leads, contacts, tasks, and settlements for the signed-in Connect user. All actions run under that user's row-level permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, list_tasks_default, create_task_default, list_contacts_default, list_settlements_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
